In [28]:
# Nearest Neighbor Classifier

import numpy as np

class NearestNeighbor:
    def __init__(self):
        """Initialize the Nearest Neighbor classifier."""
        pass

    def train(self, X, y):
        """
        Train the classifier by storing the training data.""""Python codes.ipynb"
        self.X_train = X
        self.Y_train = y

    def predict(self, X):
        """
        Predict the labels for the input data X using the nearest neighbor algorithm.""""Python codes.ipynb"
        num_test = X.shape[0]
        Ypred = np.zeros(num_test, dtype=self.Y_train.dtype)
        for i in range(num_test):
            # Compute distances between the i-th test point and all training points
            distances = np.sum(np.abs(self.X_train - X[i, :]), axis=1)
            min_index = np.argmin(distances)
            Ypred[i] = self.Y_train[min_index]
        return Ypred

NearestNeighbor = NearestNeighbor()
# Example usage:
X_train = np.array([[1, 2], [3, 4], [5, 6]])
y_train = np.array([0, 1, 0])
nn = NearestNeighbor
nn.train(X_train, y_train)
X_test = np.array([[1, 211], [180, 5]])
predictions = nn.predict(X_test)
print(predictions) 
    

[0 0]


In [ ]:
import numpy as np

# Create a 3x3 numpy matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
print(matrix)

print(matrix.shape[1]) 

np1 = np.array(())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3
